name: WWW-HugeURL
version: 0.01
abstract: Because bigger is better, right?
author: Kang-min Liu (gugod@gugod.org)
license: perl
distribution_type: module
requires:
  WWW::Mechanize: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.35
